"""
model.py — XGBoost classifier loading and inference.

SECURITY CRITICAL:
  pickle.load() is used to deserialize the trained classifier. A malicious
  .pkl file can execute arbitrary code on load. This is a known attack vector.

  Mitigation: The SHA-256 hash of the pkl bytes is verified against
  models/classifier.sha256 BEFORE calling pickle.load(). If the hash does not
  match, the process raises ModelTamperingError immediately — no model is loaded.

  Rules:
    1. NEVER accept classifier.pkl from an external source.
    2. It must ONLY be generated by backend/scripts/train_model.py on a trusted machine.
    3. models/classifier.sha256 must be committed to git as an integrity anchor.
    4. models/classifier.pkl is gitignored (binary artifact).

  See BRAIN.md: "Pickle Security Note" section.
"""

from __future__ import annotations

import hashlib
import logging
import os
import threading
from typing import TYPE_CHECKING, Final

import pandas as pd

from .feature_engineering import FEATURE_COLUMNS

if TYPE_CHECKING:
    pass  # xgboost imported lazily inside _load_model

logger = logging.getLogger(__name__)

_DEFAULT_MODEL_PATH: Final[str] = "models/classifier.pkl"
_DEFAULT_HASH_PATH: Final[str] = "models/classifier.sha256"


# ── Exceptions ───────────────────────────────────────────────────────────────

class ModelError(RuntimeError):
    """Raised when model loading or inference fails."""


class ModelTamperingError(ModelError):
    """Raised when the model file hash does not match the expected value."""


# ── Integrity verification ────────────────────────────────────────────────────

def _verify_model_integrity(model_path: str, hash_path: str) -> None:
    """
    Read pkl bytes, compute SHA-256, compare against stored hash.

    Raises:
        ModelError: If either file is missing.
        ModelTamperingError: If the hash does not match.
    """
    if not os.path.exists(hash_path):
        raise ModelError(f"Hash file not found: {hash_path!r}")
    if not os.path.exists(model_path):
        raise ModelError(f"Model file not found: {model_path!r}")

    with open(hash_path) as f:
        expected_hash = f.read().strip()

    with open(model_path, "rb") as f:
        model_bytes = f.read()

    actual_hash = hashlib.sha256(model_bytes).hexdigest()

    if actual_hash != expected_hash:
        logger.critical(
            "MODEL INTEGRITY CHECK FAILED. "
            "Expected: %s... | Got: %s...",
            expected_hash[:16], actual_hash[:16],  # partial log only
        )
        raise ModelTamperingError(
            "Classifier hash mismatch — possible model tampering detected. "
            "Regenerate with backend/scripts/train_model.py on a trusted machine."
        )

    logger.info("Model integrity verified (SHA-256 match).")


# ── Model loading ─────────────────────────────────────────────────────────────

def _load_model(model_path: str | None = None, hash_path: str | None = None):
    """
    Load and integrity-verify the XGBoost classifier.

    Args:
        model_path: Path to classifier.pkl. Falls back to MODEL_PATH env var,
                    then _DEFAULT_MODEL_PATH.
        hash_path:  Path to classifier.sha256. Falls back to MODEL_HASH_PATH env var,
                    then _DEFAULT_HASH_PATH.

    Raises:
        ModelError: On path traversal attempt, missing files, or load failure.
        ModelTamperingError: If SHA-256 hash does not match.
    """
    # Paths from env vars are the attack surface — check those for traversal/absolute
    mp_from_env = model_path is None
    hp_from_env = hash_path is None
    mp = model_path or os.environ.get("MODEL_PATH", _DEFAULT_MODEL_PATH)
    hp = hash_path or os.environ.get("MODEL_HASH_PATH", _DEFAULT_HASH_PATH)

    # Security: reject path traversal sequences in env-var-sourced paths.
    # Absolute paths are allowed (admin-level env var access implies file access).
    # Rejects MODEL_PATH=../../etc/passwd style attacks.
    for path, from_env in ((mp, mp_from_env), (hp, hp_from_env)):
        if from_env and ".." in path:
            raise ModelError(
                f"Unsafe model path rejected (directory traversal): {path!r}"
            )

    _verify_model_integrity(mp, hp)

    import pickle  # noqa: S403  # nosec B403 - hash-verified before load
    with open(mp, "rb") as f:
        model = pickle.load(f)  # noqa: S301  # nosec B301 - hash-verified before load

    logger.info("Model loaded successfully from %r", mp)
    return model


# ── Module-level cache ────────────────────────────────────────────────────────

_model_cache = None
_model_lock = threading.Lock()


def _get_model():
    """Lazily load and cache the model. Thread-safe double-checked locking."""
    global _model_cache
    if _model_cache is None:
        with _model_lock:
            if _model_cache is None:
                _model_cache = _load_model()
    return _model_cache


def _reset_model_cache() -> None:
    """Reset the module-level model cache. Used in tests only."""
    global _model_cache
    with _model_lock:
        _model_cache = None


# ── Public inference API ──────────────────────────────────────────────────────

def predict_direction(features: pd.DataFrame) -> float:
    """
    Predict the probability of a bullish outcome from feature DataFrame.

    Args:
        features: Single-row DataFrame with columns matching FEATURE_COLUMNS,
                  in the exact order defined in feature_engineering.FEATURE_COLUMNS.

    Returns:
        float in [0.0, 1.0]:
          >= 0.6  → bullish signal
          <= 0.4  → bearish signal
          0.4–0.6 → uncertain (no trade)
        Output is clamped to [0.0, 1.0] even if model returns outside range.

    Raises:
        ModelError: On missing/invalid features or model load failure.
        ModelTamperingError: If model hash verification fails on first load.
    """
    # ── Input validation ─────────────────────────────────────────────────────
    if not isinstance(features, pd.DataFrame):
        raise ModelError(f"features must be a pandas DataFrame, got {type(features).__name__}")

    if list(features.columns) != FEATURE_COLUMNS:
        raise ModelError(
            f"Feature columns mismatch.\n"
            f"  Expected: {FEATURE_COLUMNS}\n"
            f"  Got:      {list(features.columns)}"
        )

    if len(features) != 1:
        raise ModelError(
            f"Expected a single-row DataFrame for inference, got {len(features)} rows."
        )

    if features.isnull().any().any():
        null_cols = features.columns[features.isnull().any()].tolist()
        raise ModelError(f"Feature DataFrame contains NaN values in columns: {null_cols}")

    # ── Inference ────────────────────────────────────────────────────────────
    model = _get_model()
    proba_array = model.predict_proba(features)
    raw_proba = float(proba_array[0][1])  # class 1 = bullish

    # Clamp output defensively
    result = max(0.0, min(1.0, raw_proba))
    if result != raw_proba:
        logger.warning(
            "predict_proba returned out-of-range value %.6f — clamped to %.6f. "
            "This may indicate a model issue.",
            raw_proba, result,
        )

    logger.info(
        "ML prediction: %.4f (bullish=%.0f%% bearish=%.0f%%)",
        result, result * 100, (1 - result) * 100,
    )
    return result
